### ISSUE TITLE
Permissions issue when running mix release on Windows

### ISSUE THREAD

**Issue by alexjp** [bitwalker/exrm#153]
Hi,

In an app that i can build on linux, i get this error in building it in windows:
```
C:\Users\Alexandre\Desktop\serverapp>mix release
==> comeonin

Microsoft (R) Program Maintenance Utility Version 14.00.22816.0
Copyright (C) Microsoft Corporation.  All rights reserved.

'priv\bcrypt_nif.dll' is up-to-date

Compiled lib/comeonin/config.ex
Compiled lib/comeonin.ex
Compiled lib/comeonin/bcrypt_base64.ex
Compiled lib/comeonin/bcrypt.ex
Compiled lib/comeonin/password.ex
Compiled lib/comeonin/tools.ex
Compiled lib/comeonin/pbkdf2_base64.ex
Compiled lib/comeonin/pbkdf2.ex
Generated comeonin app
WARN:  Missing plugins: [rebar3_hex]
==> bbmustache (compile)
==> crmonline
Compiled lib/crmonline.ex
Compiled lib/mix/tasks/phoenix.gen.jsonapi.ex
Compiled lib/crmonline/repo.ex
Compiled lib/crmonline/primavera_repo.ex
Compiled web/web.ex
Compiled web/models/user_permission.ex
Compiled web/models/user.ex
Compiled web/models/sync/sync_resource.ex
Compiled web/models/sync/result_demonstration.ex
Compiled web/models/sync/company.ex
Compiled web/models/company.ex
Compiled web/models/result_demonstration.ex
Compiled web/controllers/page_controller.ex
Compiled web/controllers/company_controller.ex
Compiled web/controllers/consulang/bootstrap_controller.ex
Compiled web/controllers/sync/sync_resource_controller.ex
Compiled web/controllers/user_controller.ex
Compiled web/controllers/result_demonstration_controller.ex
Compiled web/views/changeset_view.ex
Compiled web/controllers/user_permission_controller.ex
Compiled web/router.ex
Compiled web/views/error_view.ex
Compiled web/views/company_view.ex
Compiled lib/crmonline/endpoint.ex
Compiled web/views/page_view.ex
Compiled web/views/layout_view.ex
Compiled web/views/result_demonstration_view.ex
Compiled web/views/user_view.ex
Compiled web/views/sync/sync_resource_view.ex
Compiled web/views/user_permission_view.ex
Generated crmonline app
Consolidated Timex.Date.Convert
Consolidated Poison.Decoder
Consolidated Poison.Encoder
Consolidated Plug.Exception
Consolidated Phoenix.HTML.FormData
Consolidated Phoenix.HTML.Safe
Consolidated Phoenix.Param
Consolidated Ecto.Queryable
Consolidated Access
Consolidated Collectable
Consolidated Enumerable
Consolidated Inspect
Consolidated List.Chars
Consolidated Range.Iterator
Consolidated String.Chars
Consolidated protocols written to _build/prod/consolidated
** (File.Error) could not remove files and directories recursively from c:/Users
/Alexandre/Desktop/serverapp/_build/prod/lib: permission denied
    (elixir) lib/file.ex:837: File.rm_rf!/1
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    lib/mix/tasks/release.ex:58: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6


C:\Users\Alexandre\Desktop\serverapp>
```

dont understand why the complaining of permissions.

Thanks !

**Comment by bitwalker** [comment]
@alexjp Currently exrm hasn't provided the boot script for Windows (next on my TODO list here), so your release would not have been usable on Windows anyway, but as far as the permissions issue goes, I'm not at all sure why that would occur, but when I begin testing the Windows support I can test further.

As a Windows dev myself for my day job, debugging permissions issues is a frustrating experience, so I feel your pain :(

**Comment by bitwalker** [comment]
Oh, could you confirm what version of Windows this occurred on?

**Comment by alexjp** [comment]
Hi,

Sure, its a virtual machine in windows 7 32bit. Its where I work, every time i need Windows.
I tried putting the project on the desktop, on public folders, changing permissions to full control, etc.

Could a file to be deleted still be in use ?

I develop in Linux and my workaround is to deploy on the clients servers with a virtual machine. Its not that I like to use Windows, but it would be a life (work life that is) savior !

**Comment by bitwalker** [comment]
I just pushed version 0.18.1, which adds support for building releases on Windows. I was able to successfully build and run a release on my Windows 10 dev machine, but I'll need assistance from you and others to determine whether it's solid.

I pushed a fix for the bug this issue was about as well, so I am closing it for now.
