### ISSUE TITLE
ReleaseManager.Deps.get_applications expects packages to have only 1 file matching **/*.app.src

### ISSUE THREAD

**Issue by antipax** [bitwalker/exrm#246]
Getting this for my project which uses the gproc hex package on latest master:

```
** (CaseClauseError) no case clause matching: ["/Users/ericentin/Documents/Code/turbo/deps/gproc/patches/kernel/kernel.app.src", "/Users/ericentin/Documents/Code/turbo/deps/gproc/src/gproc.app.src"]
    lib/exrm/deps.ex:186: ReleaseManager.Deps.get_applications/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/exrm/deps.ex:140: ReleaseManager.Deps.get_included_applications/1
    lib/exrm/deps.ex:129: ReleaseManager.Deps.get_implicit_applications/1
    lib/exrm/deps.ex:13: ReleaseManager.Deps.get_missing_applications/2
    lib/exrm/deps.ex:48: ReleaseManager.Deps.print_missing_applications/1
```

Looks like it's expecting there to only be one .app.src file in the dep directory.

**Comment by bitwalker** [comment]
Damn, thanks for reporting this, I was testing with a few apps, but I guess none of them had more than a single app.src file. I'll get a fix pushed ASAP.

**Comment by antipax** [comment]
No problem. Thanks again for your hard work on exrm!

**Comment by bitwalker** [comment]
I pushed the fix for this and also pushed a new release to hex (1.0.0-rc3). Let me know if you run into any other hiccups!
