### ISSUE TITLE
Error in :filename.join generating .tar

### ISSUE THREAD

**Issue by bradurani** [bitwalker/exrm#378]
I have an error which occurs after a successful build, it would seem, I think when it tries to create the .tar file

```
 % MIX_ENV=dev mix release
==> dashboard
Compiling 30 files (.ex)
warning: variable headers is unused
  web/oauth/oauth2client.ex:13

warning: unused alias Path
  web/controllers/path_controller.ex:4

Generated dashboard app
==> woodpecker
Compiling 9 files (.ex)
Generated woodpecker app
Building release with MIX_ENV=dev.
==> The release for dashboard-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/dashboard/bin/dashboard console`
Building release with MIX_ENV=dev.
** (FunctionClauseError) no function clause matching in :filename.join/2
    (stdlib) filename.erl:407: :filename.join({:error, :bad_name}, 'templates')
    (stdlib) filename.erl:394: :filename.join/1
    /Users/bradurani/src/bumbershoot/deps/relx/src/rlx_util.erl:180: :rlx_util.find_priv_templates/0
    /Users/bradurani/src/bumbershoot/deps/relx/src/rlx_util.erl:177: :rlx_util.template_files/0
    /Users/bradurani/src/bumbershoot/deps/relx/src/rlx_prv_assembler.erl:645: :rlx_prv_assembler.render/2
    /Users/bradurani/src/bumbershoot/deps/relx/src/rlx_prv_assembler.erl:642: :rlx_prv_assembler.include_nodetool/1
    /Users/bradurani/src/bumbershoot/deps/relx/src/rlx_prv_assembler.erl:354: :rlx_prv_assembler.write_bin_file/4
    /Users/bradurani/src/bumbershoot/deps/relx/src/rlx_prv_assembler.erl:59: :rlx_prv_assembler.do/1
    /Users/bradurani/src/bumbershoot/deps/relx/src/relx.erl:308: :relx.run_provider/2
    (stdlib) lists.erl:1262: :lists.foldl/3
    /Users/bradurani/src/bumbershoot/deps/relx/src/relx.erl:291: :relx.run_providers_for_actions/2
    lib/exrm/utils/utils.ex:105: ReleaseManager.Utils.relx/5
    lib/mix/tasks/release.ex:339: anonymous fn/4 in Mix.Tasks.Release.do_release/1
    lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2
    lib/ex_unit/capture_io.ex:119: ExUnit.CaptureIO.do_capture_io/3
    lib/mix/tasks/release.ex:338: Mix.Tasks.Release.do_release/1
    lib/mix/tasks/release.ex:78: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/project.ex:211: Mix.Project.in_project/4
    (elixir) lib/file.ex:1145: File.cd!/2
    lib/mix/tasks/release.ex:57: anonymous fn/3 in Mix.Tasks.Release.run/1
```

This is building from an umbrella app with 2 phoenix apps in the `apps` folder. Thanks!

**Comment by bitwalker** [comment]
Looks like an issue in relx, but I'll need some details to help determine that for sure. Could you run with `--verbosity=verbose`?

In the meantime, take a look at [distillery](https://github.com/bitwalker/distillery). It's what I've been working on to replace exrm, and this issue shouldn't be present there.

**Comment by joshuaswilcox** [comment]
I have been getting this lately too here is the verbose output
```
===> tarball /var/www/scotchy/rel/scotchy/scotchy-0.0.11.tar.gz successfully created!
===> Provider successfully run: tar

==> Generating nodetool...
==> Packaging release...
** (FunctionClauseError) no function clause matching in :filename.join/1
    (stdlib) filename.erl:395: :filename.join([])
    (stdlib) erl_tar.erl:471: :erl_tar.split_filename/4
    (stdlib) erl_tar.erl:400: :erl_tar.create_header/3
    (stdlib) erl_tar.erl:323: :erl_tar.add1/4
    (stdlib) erl_tar.erl:1000: :erl_tar.foreach_while_ok/2
    (stdlib) erl_tar.erl:132: :erl_tar.create/3
    lib/mix/tasks/release.ex:420: Mix.Tasks.Release.update_release_package/1
    lib/mix/tasks/release.ex:82: Mix.Tasks.Release.do_run/1
```
full Gist https://gist.github.com/joshuaswilcox/4e74d56c8e24e768155b6d4cfa4b0c7c

Going to take a look at distillery now, though
