### ISSUE TITLE
Running mix release in docker cause MatchError.

### ISSUE THREAD

**Issue by chenxsan** [bitwalker/exrm#397]
I'm building my project inside docker:

```
sh-4.2# MIX_ENV=prod mix do deps.get, phoenix.digest, compile, release
Running dependency resolution
All dependencies up to date
Check your digested files at "priv/static"
Building release with MIX_ENV=prod.
** (MatchError) no match of right hand side value: {:error, {:bad_file_type, '/home/myProjects/news/rel/news/var/erl_pipes/news@127.0.0.1/erlang.pipe.1.r', :other}}
    lib/mix/tasks/release.ex:420: Mix.Tasks.Release.update_release_package/1
    lib/mix/tasks/release.ex:82: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```
OS in docker: CentOS 7, Elixir 1.3.4, Erlang 19.1.

No server is running.

**Comment by chenxsan** [comment]
Guess something is wrong with the `rel` folder, after I remove it, everything works now.
