### ISSUE TITLE
':logger application is not running' after an upgrade

### ISSUE THREAD

**Issue by rubencaro** [bitwalker/exrm#78]
My `mix.exs` looks like:
```elixir
  def application do
    [applications: [:logger, :cowboy, :plug, :emysql],
     included_applications: [:jazz, :cipher],
     mod: {Sequeler, []}]
  end
```
Everything looks fine with the first release. Then I build a second release, and make an upgrade. I get this:

```
Release 1.0.0+20141123_53e045e not found, attempting to unpack releases/1.0.0+20141123_53e045e/sequeler.tar.gz
Unpacked successfully: "1.0.0+20141123_53e045e"
Installed Release: 1.0.0+20141123_53e045e
Made release permanent: "1.0.0+20141123_53e045e"
```

Everything still looks ok. I run `bin/sequeler attach` and I see everything is up, `:emysql`, `:cipher`, `:jazz`, `:cowboy`, `:plug`... The only one that's not responding is `:logger`. 

When I run `Logger.info "hi"` I get:

```
** (RuntimeError) Cannot use Logger, the :logger application is not running
    (logger) lib/logger/config.ex:50: Logger.Config.__data__/0
    (logger) lib/logger.ex:401: Logger.log/3
```

The trace in logs for a regular http call to the main app may give you more clues:

```
=CRASH REPORT==== 23-Nov-2014::03:48:13 ===
  crasher:
    initial call: Elixir.Logger.Watcher:init/1
    pid: <0.66.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.RuntimeError',
                       message => <<"Cannot use Logger, the :logger application is not running">>},
                     [{'Elixir.Logger.Config','__data__',0,
                          [{file,"lib/logger/config.ex"},{line,50}]},
                      {'Elixir.Logger',log,3,
                          [{file,"lib/logger.ex"},{line,401}]},
                      {'Elixir.Logger.Watcher',handle_info,2,
                          [{file,"lib/logger/watcher.ex"},{line,92}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,599}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,237}]}]}
      in function  gen_server:terminate/6 (gen_server.erl, line 737)
    ancestors: ['Elixir.Logger.Supervisor',<0.60.0>]
    messages: []
    links: [<0.61.0>,<0.6.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 16236
  neighbours:

=SUPERVISOR REPORT==== 23-Nov-2014::03:48:13 ===
     Supervisor: {local,'Elixir.Logger.Supervisor'}
     Context:    child_terminated
     Reason:     {#{'__exception__' => true,
                    '__struct__' => 'Elixir.RuntimeError',
                    message => <<"Cannot use Logger, the :logger application is not running">>},
                  [{'Elixir.Logger.Config','__data__',0,
                       [{file,"lib/logger/config.ex"},{line,50}]},
                   {'Elixir.Logger',log,3,[{file,"lib/logger.ex"},{line,401}]},
                   {'Elixir.Logger.Watcher',handle_info,2,
                       [{file,"lib/logger/watcher.ex"},{line,92}]},
                   {gen_server,handle_msg,5,
                       [{file,"gen_server.erl"},{line,599}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,237}]}]}
     Offender:   [{pid,<0.66.0>},
                  {name,'Elixir.Logger.ErrorHandler'},
                  {mfargs,
                      {'Elixir.Logger.Watcher',watcher,
                          [error_logger,'Elixir.Logger.ErrorHandler',
                           {true,false,500},
                           link]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]


nil

```

This is right after the `upgrade`. Before that everything worked ok.

Did I miss something?

**Comment by fishcakez** [comment]
@rubencaro it has been merged on v1.0 and master branches, 1.0.3 is out soon.

**Comment by bitwalker** [comment]
@fishcakez Thanks for updating, just caught up on a bunch of my emails today, glad this one is finally being resolved.

**Comment by rubencaro** [comment]
Nice! Thanks guys.
